spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6397
      database: 0
      jedis:
        pool:
          max-active: 50
          max-wait: -1
          max-idle: 20
          min-idle: 2
      timeout: 5000

server:
  port: 8070

mybatis-plus:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.project.myblog.mybatis.entity
